dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
      - cmake
script:
  # Link gcc-10 and g++-10 to their standard commands
  - ln -s /usr/bin/gcc-10 /usr/local/bin/gcc
  - ln -s /usr/bin/g++-10 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-10
  - export CXX=/usr/bin/g++-10
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  - cmake cmake --build . --config Release
